version: '3.7'

services:
  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: /bin/sh -c "fresh"
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    volumes:
      - ./app:/go/src/app
    depends_on:
      - database

  database:
    image: mysql:8.0.22
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
